name: Deploy React App to GitHub Pages (peaceiris)

on:
  push:
    branches:
      - main

# Give the GITHUB_TOKEN write permission so the action can push to gh-pages
permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Debug git remote (optional - remove if you don't want logs)
        run: |
          echo "GITHUB_ACTOR=${GITHUB_ACTOR}"
          git --version
          git remote -v

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          CI: "false"
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
